#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'p:lavender'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

[[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:surface2'
    background = 'transparent'
    template = " {{ .HEAD }}{{if .BranchStatus }} {{.BranchStatus}}{{ end }}"

[blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true
  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:surface2'
    background = 'transparent'
foreground_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}p:sapphire{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}",
  "{{ if gt .Ahead 0 }}p:green{{ end }}",
  "{{ if gt .Behind 0 }}p:yellow{{ end }}"
]
template = "{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}"
    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    foreground = 'p:sky'
    background = 'transparent'
    template = '{{ if .Venv }}({{ .Venv }}){{ end }}'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:yellow'
    background = 'transparent'
    template = ' {{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}p:red{{end}}",
      "{{if eq .Code 0}}p:green{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}p:red{{end}}",
    "{{if eq .Code 0}}p:green{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'p:green'
  background = 'transparent'
  template = '❯❯ '

[palette]
  rosewater = '#f5e0dc'
  flamingo = '#f2cdcd'
  pink = '#f5c2e7'
  mauve = '#cba6f7'
  red = '#f38ba8'
  maroon = '#eba0ac'
  peach = '#fab387'
  yellow = '#f9e2af'
  green = '#a6e3a1'
  teal = '#94e2d5'
  sky = '#89dceb'
  sapphire = '#74c7ec'
  blue = '#89b4fa'
  lavender = '#b4befe'
  text = '#cdd6f4'
  subtext1 = '#bac2de'
  subtext0 = '#a6adc8'
  overlay2 = '#9399b2'
  overlay1 = '#7f849c'
  overlay0 = '#6c7086'
  surface2 = '#585b70'
  surface1 = '#45475a'
  surface0 = '#313244'
  base = '#1e1e2e'
  mantle = '#181825'
  crust = '#11111b'
